// type normal
export const GET_CINEMA_LIST = "GET_CINEMA_LIST";
export const GET_SHOWTIMES_FILM = "GET_SHOWTIMES_FILM";
export const GET_SHOWTIMES_FILM_CINEMA = "GET_SHOWTIMES_FILM_CINEMA";
export const POST_NEW_SHOWTIME = "POST_NEW_SHOWTIME";

// type saga
export const GET_CINEMA_LIST_SAGA = "GET_CINEMA_LIST_SAGA";
export const GET_SHOWTIMES_FILM_SAGA = "GET_SHOWTIMES_FILM_SAGA";
export const GET_SHOWTIMES_FILM_CINEMA_SAGA = "GET_SHOWTIMES_FILM_CINEMA_SAGA";
export const POST_NEW_SHOWTIME_SAGA = "POST_NEW_SHOWTIME_SAGA";
