export const DISLAY_LOADING = "DISLAY_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
export const DISLAY_LOADING_MODAL = "DISLAY_LOADING_MODAL";
export const HIDE_LOADING_MODAL = "HIDE_LOADING_MODAL";
