// type normal
export const GET_MOVIE_LIST = "GET_MOVIE_LIST";
export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL";
export const POST_NEW_MOVIE = "POST_NEW_MOVIE";
export const POST_UPDATE_MOVIE = "POST_UPDATE_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";

// type saga
export const GET_MOVIE_LIST_SAGA = "GET_MOVIE_LIST_SAGA";
export const GET_MOVIE_DETAIL_SAGA = "GET_MOVIE_DETAIL_SAGA";
export const POST_NEW_MOVIE_SAGA = "POST_NEW_MOVIE_SAGA";
export const POST_UPDATE_MOVIE_SAGA = "POST_UPDATE_MOVIE_SAGA";
export const DELETE_MOVIE_SAGA = "DELETE_MOVIE_SAGA";
